### ISSUE TITLE
Not pure nor div-customisable

### ISSUE THREAD

**Issue by davidpelayo** [rwu823/react-tag#2]
It would be nice to have it in pure stateless react function as well as the type of component would be nice to be informed by props, rather than always a div. Don't you think?

**Comment by onedesert** [comment]
Proposal https://github.com/rwu823/react-div/pull/3

**Comment by rwu823** [comment]
It will be implemented in next version.

**Comment by rwu823** [comment]
Please check the v2 version, now rename to `react-tag` :)

**Comment by davidpelayo** [comment]
Then, issues for upgrading the documentation should be created, shouldn't they?

**Comment by rwu823** [comment]
@davidpelayo 

Welcome to `Pull Request` with that.
